import { logger } from '../utils/logger';

export interface HistoryRecord {
  timestamp: string;
  sensorId: string;
  sensorName: string;
  temperature: number;
  humidity: number;
  soilMoisture: number;
  ph: number;
  status: 'online' | 'offline';
}

export const generateCSV = (records: HistoryRecord[]): string => {
  const headers = ['Timestamp', 'Sensor ID', 'Sensor Name', 'Temperature (°C)', 'Humidity (%)', 'Soil Moisture (%)', 'pH', 'Status'];
  const rows = records.map(r => [
    r.timestamp,
    r.sensorId,
    r.sensorName,
    r.temperature.toFixed(1),
    r.humidity.toFixed(1),
    r.soilMoisture.toFixed(1),
    r.ph.toFixed(1),
    r.status
  ]);
  
  const csv = [headers, ...rows].map(row => row.join(',')).join('\n');
  logger.info(`✅ Generated CSV with ${records.length} records`);
  return csv;
};

export const generateJSON = (records: HistoryRecord[]): string => {
  logger.info(`✅ Generated JSON with ${records.length} records`);
  return JSON.stringify({
    exportDate: new Date().toISOString(),
    totalRecords: records.length,
    data: records
  }, null, 2);
};

export const generateHTML = (records: HistoryRecord[]): string => {
  const tableRows = records.map(r => `
    <tr>
      <td>${r.timestamp}</td>
      <td>${r.sensorId}</td>
      <td>${r.sensorName}</td>
      <td>${r.temperature.toFixed(1)}°C</td>
      <td>${r.humidity.toFixed(1)}%</td>
      <td>${r.soilMoisture.toFixed(1)}%</td>
      <td>${r.ph.toFixed(1)}</td>
      <td>${r.status}</td>
    </tr>
  `).join('');

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>AgroTech Sensor History Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 20px; }
    h1 { color: #10b981; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { padding: 12px; text-align: left; border: 1px solid #ddd; }
    th { background-color: #10b981; color: white; }
    tr:nth-child(even) { background-color: #f8fafc; }
    .footer { margin-top: 20px; color: #64748b; font-size: 12px; }
  </style>
</head>
<body>
  <h1>🌾 AgroTech Sensor History Report</h1>
  <p><strong>Export Date:</strong> ${new Date().toLocaleString()}</p>
  <p><strong>Total Records:</strong> ${records.length}</p>
  <table>
    <thead>
      <tr>
        <th>Timestamp</th>
        <th>Sensor ID</th>
        <th>Sensor Name</th>
        <th>Temperature</th>
        <th>Humidity</th>
        <th>Soil Moisture</th>
        <th>pH</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      ${tableRows}
    </tbody>
  </table>
  <div class="footer">
    <p>Generated by AgroTech Platform | © 2026 AgroMind</p>
  </div>
</body>
</html>
  `;
  
  logger.info(`✅ Generated HTML report with ${records.length} records`);
  return html;
};
